### ISSUE TITLE
[Fix] QA 반영

### ISSUE THREAD

**Issue by duyeong-ko** [team-peekabook/Peekabook-iOS#124]
## 🛠 Issue

- QA 반영하겠습니다

## 📝 To-do

- [ ] (p1) 책 등록뷰 등 키보드 착붙 (0/200) 라벨 보이게
- [x] (p1) 책 등록뷰 텍스트뷰 3글자 입력
- [x] (p2) 책 등록 뒤로가기 누를시 메인뷰로 이동
- [x] (p2) 글자수와 글자수 라벨 같게
- [x] (p3) 텍스트검색 힌트 수정
- [ ] (p3) 책 추천 텍스트뷰 붙여넣기시 200자에서 애매하게 되고 카운트도 멈춤
