### ISSUE TITLE
[Chore] 레이아웃 조정

### ISSUE THREAD

**Issue by devxsby** [team-peekabook/Peekabook-iOS#138]
## 🛠 Issue
- [x] 레이아웃 조정 (책 수정뷰, 책 작성 뷰 텍스트뷰 키보드 올라올때 상태에 맞추어 높이기)
- [x] 책 상세보기 (유저, 친구 타입 분기처리)
- [ ] 바텀 책장 자동 접힘 막기
- [x] 작가이름 여러명일때 ^문자열로 spilit 하기
- [x] 네이버 책검색 실패시 앱 강제종료, 테이블 뷰 리로드
- [x] 마이페이지 뷰 추가
- [ ] 책 등록 후 상세보기뷰로 전환

## 📝 To-do

- [x] 코드작성
