### ISSUE TITLE
[Refactor] 추천탭 뷰 코드 리팩토링

### ISSUE THREAD

**Issue by 6uohul** [team-peekabook/Peekabook-iOS#152]
## 🛠 Issue

추천한 책, 추천받은 책 뷰 코드 리팩토링

## 📝 To-do

- [x] 책 제목 글자수 레이아웃 수정
- [x] 좌->우 스크롤 방향 수정
- [x] 추천사 줄바꿈 많은 경우 처리
