### ISSUE TITLE
[Fix] 책장 비었을때 관련 오류

### ISSUE THREAD

**Issue by 6uohul** [team-peekabook/Peekabook-iOS#253]
## 🛠 Issue

- 내 책장이 빈 경우 책 추천하기 안되는 에러 헤결
- 내 책장 비었을때 친구 뷰에서 내 책장 엠티뷰가 뜨는 오류

분기처리 체크할 것 + 친구책장/ 내책장왔다갔다 오류 없는지 체크
- [ ] 내 책장 비었을때 내 책 뷰 엠티뷰 / 픽 수정 x
- [ ] 친구 책장 비었을 시 친구 책장 뷰 엠티뷰 / 책 추천은 늘 가능
- [ ] 내, 친구 pick과 바텀 책장 비었을 시 해당 엠티뷰

## 📝 To-do
- [ ] 에러 해결
