### ISSUE TITLE
[Feat] 1차 스프린트 기능 구현

### ISSUE THREAD

**Issue by duyeong-ko** [team-peekabook/Peekabook-iOS#282]
## 📝 To-do

- [x] 친구 뷰에서 메모뷰 안보이게
- [x] 텍스트 검색 버튼 개선
- [x] 메모 placeholder 수정
- [x] 책장 0Books일때 바텀시트 고정
- [x] 동일 도서 중복 등록 막기
